DROP TABLE Pracownicy CASCADE CONSTRAINTS;
DROP TABLE Brygady CASCADE CONSTRAINTS;
DROP TABLE Klienci CASCADE CONSTRAINTS;
DROP TABLE Dostawcy CASCADE CONSTRAINTS;
DROP TABLE Narzedzia CASCADE CONSTRAINTS;
DROP TABLE Narzedzia_wypozyczenia CASCADE CONSTRAINTS;
DROP TABLE Materialy CASCADE CONSTRAINTS;
DROP TABLE Zamowienia_materialow CASCADE CONSTRAINTS; 
DROP TABLE Budynki CASCADE CONSTRAINTS;
DROP TABLE Zlecenia_budowy CASCADE CONSTRAINTS;
DROP TABLE Reklamacje CASCADE CONSTRAINTS;
DROP TABLE dl_zam CASCADE CONSTRAINTS;  --tabelki pomocniczne 
DROP TABLE temp CASCADE CONSTRAINTS;    --do kwerend
DROP TABLE brygadzisci CASCADE CONSTRAINTS;   --dodatkowa tabelka ze skryptu modyfikujacego
DROP TABLE pojazdy_sluzbowe CASCADE CONSTRAINTS;
DROP TABLE wypozyczenia_pojazdow CASCADE CONSTRAINTS;
    


    